.TH "Clocks" 3 "Sun Dec 16 2018" "Gameboy Emulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Clocks \- Structure containing information about the clock\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cpu\&.hpp>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBm_cycles\fP"
.br
.ti -1c
.RI "int \fBt_cycles\fP"
.br
.ti -1c
.RI "int \fBdivide_counter\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure containing information about the clock\&. 
.SH "Field Documentation"
.PP 
.SS "int Clocks::m_cycles"
Machine cycle, usually taking about 3 and 6 clock periods - t_cycles 
.SS "int Clocks::t_cycles"
Clock periods 

.SH "Author"
.PP 
Generated automatically by Doxygen for Gameboy Emulator from the source code\&.
