.TH "DebuggerCommand" 3 "Sun Dec 16 2018" "Gameboy Emulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DebuggerCommand \- Structure containing parsed debugger command\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <debugger\&.hpp>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBCommand\fP \fBcmd\fP"
.br
.ti -1c
.RI "\fBArguments\fP \fBargs\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure containing parsed debugger command\&. 
.SH "Field Documentation"
.PP 
.SS "\fBArguments\fP DebuggerCommand::args"
Vector of arguemts 
.SS "\fBCommand\fP DebuggerCommand::cmd"
Enum of command 

.SH "Author"
.PP 
Generated automatically by Doxygen for Gameboy Emulator from the source code\&.
