.TH "DebuggerState" 3 "Sun Dec 16 2018" "Gameboy Emulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DebuggerState \- Structure containing information about the state of debugger\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <debugger\&.hpp>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "bool \fBdebugging\fP"
.br
.ti -1c
.RI "bool \fBstep_set\fP"
.br
.ti -1c
.RI "unsigned int \fBstepper_count\fP"
.br
.ti -1c
.RI "bool \fBbreakpoint_set\fP"
.br
.ti -1c
.RI "uint16_t \fBbreakpoint\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure containing information about the state of debugger\&. 
.SH "Field Documentation"
.PP 
.SS "uint16_t DebuggerState::breakpoint"
Address where to set breakpoint 
.SS "bool DebuggerState::breakpoint_set"
Is breakpoint set 
.SS "bool DebuggerState::debugging"
Is the debugger running 
.SS "bool DebuggerState::step_set"
Is stepping set 
.SS "unsigned int DebuggerState::stepper_count"
How much steps to run 

.SH "Author"
.PP 
Generated automatically by Doxygen for Gameboy Emulator from the source code\&.
