.TH "DebuggerState" 3 "Thu Dec 6 2018" "Gameboy Emulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DebuggerState
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "bool \fBdebugging\fP"
.br
.ti -1c
.RI "bool \fBstep_set\fP"
.br
.ti -1c
.RI "unsigned int \fBstepper_count\fP"
.br
.ti -1c
.RI "bool \fBbreakpoint_set\fP"
.br
.ti -1c
.RI "uint16_t \fBbreakpoint\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Gameboy Emulator from the source code\&.
