.TH "Debugger" 3 "Thu Dec 6 2018" "Gameboy Emulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Debugger
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDebugger\fP (\fBGameboy\fP &gameboy_state)"
.br
.ti -1c
.RI "void \fBDebug\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Gameboy Emulator from the source code\&.
