.TH "Gameboy" 3 "Thu Dec 6 2018" "Gameboy Emulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Gameboy
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGameboy\fP (bool debug, bool without_boot, bool exit_on_inifite, std::string rom_file)"
.br
.ti -1c
.RI "void \fBLoop\fP ()"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBDebugger\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Gameboy Emulator from the source code\&.
