.TH "src/gpu/gpu.hpp" 3 "Thu Dec 6 2018" "Gameboy Emulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/gpu/gpu.hpp \- Graphical Processing Unit of \fBGameboy\fP\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <memory>\fP
.br
\fC#include <SDL2/SDL\&.h>\fP
.br
\fC#include '\&.\&./memory/memory\&.hpp'\fP
.br
\fC#include '\&.\&./helper/helper\&.hpp'\fP
.br
\fC#include '\&.\&./cpu/cpu\&.hpp'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBGPU\fP"
.br
.RI "Class containing logic of \fBGPU\fP\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const int \fBSCREEN_HEIGH\fP = 320"
.br
.ti -1c
.RI "const int \fBSCREEN_WIDTH\fP = 288"
.br
.in -1c
.SH "Detailed Description"
.PP 
Graphical Processing Unit of \fBGameboy\fP\&. 


.PP
\fBAuthor:\fP
.RS 4
w3ndige (w3ndige@protonmail.com) 
.RE
.PP
\fBVersion:\fP
.RS 4
0\&.1 
.RE
.PP
\fBDate:\fP
.RS 4
2018-12-06
.RE
.PP
\fBCopyright:\fP
.RS 4
Copyright (c) 2018 
.RE
.PP

.SH "Variable Documentation"
.PP 
.SS "const int SCREEN_HEIGH = 320"
Height of screen 
.SS "const int SCREEN_WIDTH = 288"
Width of screen 
.SH "Author"
.PP 
Generated automatically by Doxygen for Gameboy Emulator from the source code\&.
