.TH "OpcodeInfo" 3 "Thu Dec 6 2018" "Gameboy Emulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OpcodeInfo
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "std::string \fBdisassembled\fP"
.br
.ti -1c
.RI "uint16_t \fBjump_offset\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Gameboy Emulator from the source code\&.
