.TH "Register" 3 "Thu Dec 6 2018" "Gameboy Emulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Register
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint16_t \fBpair\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint8_t \fBlow\fP"
.br
.ti -1c
.RI "   uint8_t \fBhigh\fP"
.br
.ti -1c
.RI "}; "
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Gameboy Emulator from the source code\&.
